/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconLogosTiktok: (typeof import("~icons/logos/tiktok.jsx"))["default"];
  const IconMdiAccountBox: (typeof import("~icons/mdi/account-box.jsx"))["default"];
  const IconMdiAccountCircleOutline: (typeof import("~icons/mdi/account-circle-outline.jsx"))["default"];
  const IconMdiChevronDown: (typeof import("~icons/mdi/chevron-down.jsx"))["default"];
  const IconMdiClose: (typeof import("~icons/mdi/close.jsx"))["default"];
  const IconMdiFacebook: (typeof import("~icons/mdi/facebook.jsx"))["default"];
  const IconMdiInstagram: (typeof import("~icons/mdi/instagram.jsx"))["default"];
  const IconMdiMagnify: (typeof import("~icons/mdi/magnify.jsx"))["default"];
  const IconMdiMenu: (typeof import("~icons/mdi/menu.jsx"))["default"];
  const IconMdiMicrosoftXboxControllerMenu: (typeof import("~icons/mdi/microsoft-xbox-controller-menu.jsx"))["default"];
}
