/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconMdiMagnify: typeof import('~icons/mdi/magnify.jsx')['default']
}
