name: Playwright Tests
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Inspect env vars
        run: env
      - name: Build the app
        run: pnpm run build
        env:
          MAPBOX_AUTOCOMPLETE_ACCESS_TOKEN: ${{ secrets.MAPBOX_AUTOCOMPLETE_ACCESS_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          STYTCH_PROJECT_ID: ${{ secrets.STYTCH_PROJECT_ID }}
          STYTCH_PROJECT_SECRET: ${{ secrets.STYTCH_PROJECT_SECRET }}
          SWELL_SECRET_KEY: ${{ secrets.SWELL_SECRET_KEY }}
          SWELL_STORE_ID: ${{ secrets.SWELL_STORE_ID }}
      - name: Run Playwright tests
        env:
          MAPBOX_AUTOCOMPLETE_ACCESS_TOKEN: ${{ secrets.MAPBOX_AUTOCOMPLETE_ACCESS_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          STYTCH_PROJECT_ID: ${{ secrets.STYTCH_PROJECT_ID }}
          STYTCH_PROJECT_SECRET: ${{ secrets.STYTCH_PROJECT_SECRET }}
          SWELL_SECRET_KEY: ${{ secrets.SWELL_SECRET_KEY }}
          SWELL_STORE_ID: ${{ secrets.SWELL_STORE_ID }}
        run: pnpm exec playwright test --forbid-only -c ./playwright.config.ts
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
