name: Playwright Tests
on: push
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
      - name: Install dependencies and Playwright Browsers
        run: |
          pnpm install
          npx playwright install --with-deps
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - name: Run Playwright tests
        env:
          BASE_URL: $(echo "https://"$(echo "${{ steps.branch-name.outputs.current_branch }}" | sed 's/[^a-zA-Z0-9]/-/g')".goodpluck.pages.dev")
        run: echo $BASE_URL && npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
