name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - name: echo branch url
        run: echo "https://${{ steps.branch-name.outputs.current_branch }}.goodpluck.pages.dev"
      - name: cloudflare-preview-url
        uses: zentered/cloudflare-preview-url@v1.0.0
        id: cloudflare_preview_url
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_EMAIL: ${{ secrets.CLOUDFLARE_ACCOUNT_EMAIL }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        with:
          cloudflare_project_id: "repo-name"
      - name: Get URL
        run: echo "https://${{ steps.cloudflare_preview_url.outputs.preview_url }}" | sed 's/[^a-zA-Z0-9]/-/g'
      - name: Run Playwright tests
        env:
          BASE_URL: $(echo "https://${{ steps.branch-name.outputs.current_branch }}.goodpluck.pages.dev" | sed 's/[^a-zA-Z0-9]/-/g')
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
