name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7
      - name: echo branch url
        run: echo "https://${{ steps.branch-name.outputs.current_branch }}.goodpluck.pages.dev"
      - name: Run Playwright tests
        env:
          BASE_URL: "https://${{ steps.branch-name.outputs.current_branch }}.goodpluck.pages.dev"
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
