name: Run Unit Tests
on:
  push:
jobs:
  build:
    runs-on: buildjet-4vcpu-ubuntu-2204
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install dependencies
        run: pnpm i
      - name: Run tests
        run: npx vitest
